### ISSUE TITLE
Interested in maintaining

### ISSUE THREAD

**Issue by mfikes** [RickMoynihan/lein-tools-deps#14]
Hey @RickMoynihan, this looks like a really cool and also important (IMHO) project. Are you still interested in maintaining it and pushing it forward?

If not, I'd love to contribute to making it become a thing. What are your thoughts? Would you prefer to take PRs, or would you prefer to transfer the project to a new owner? (I'd be willing to take it on if so.)

**Comment by RickMoynihan** [comment]
Hi @mfikes, thanks for your kind words.  

I'd definitely be very happy for some help pushing this on, and I'm hoping that I'll now have a little more time to develop it.

I've tried bumping things along a bit today, mainly version bumping things and taking a stab at resolving issue #6.

However I have just moved house, and now have a new todo list to get through; so I guess we'll see how I get on! :-)

If you were to help maintain this, what features/changes/ideas do you you have for developing it?  Answers in issues would be perfect!  :-)

**Comment by mfikes** [comment]
@RickMoynihan I don't currently have any specific ideas, other than a recognition that this particular project would be extremely valuable to the community, and a willingness to "roll up my sleeves" and help make it happen. I haven't even tried using it yet, and will give it a shot as I have some projects where it would be useful. I'll help push things forward via comments and PRs.

**Comment by RickMoynihan** [comment]
Well I'm very open to contributions and feedback.  

I'm not at all an expert in this or tools.deps either though, and just created the project in some freetime because I also thought it'd be useful; however I don't currently use the project for anything, but see the need for something like this to transition to the new cli and deps.edn stuff Alex Miller is doing.

I think adding support for git deps, and local deps etc is probably a priority.

Anyway I'm looking forward to discussing things further and figuring out how it might work in practice, e.g. tools.deps aliases etc.
