### ISSUE TITLE
Allow for no project-level deps.edn

### ISSUE THREAD

**Issue by mfikes** [RickMoynihan/lein-tools-deps#15]
If `:tools/deps` is set to `[:system :home]` then things should work, but one bit that needs to be revised is this bit of code

```
(def deps-file (io/file (config-files 2)))
```

Currently it is assuming `config-files` is a vector with 3 elements and causes a `java.lang.IndexOutOfBoundsException` if there is no `deps.edn` sitting in the working directory.

**Comment by RickMoynihan** [comment]
Yeah that's pretty gross.  I just made the smallest change from what I had before using the new tools.deps API.

I think we'll need to move that out of the top level, bind/handle it inside canonicalise-dep-refs.

https://github.com/RickMoynihan/lein-tools-deps/blob/master/src/lein_tools_deps/plugin.clj#L30

I don't have time to fix this just now, but will fix it when I get chance or take a patch :-)

**Comment by RickMoynihan** [comment]
Hey @mfikes, thanks for the PR.  I took a look at it, but I think there are a few other potential corner cases that led me to take a different route.

In particular it turns out that `reader/clojure-env` causes a side effect by shelling out to the command line tool, so I wasn't particularly comfortable doing that at read-time.  Also I figured we'd need a similar guard over the `:home` file.

Finally I thought I'd add a little bit of error checking with messages to clarify the allowed values in `:tools/deps`.
