### ISSUE TITLE
Supporting deps.edn aliases

### ISSUE THREAD

**Issue by RickMoynihan** [RickMoynihan/lein-tools-deps#4]
How should we handle profiles in leiningen and deps.edn aliases?

Could deps.edn aliases be combined into leiningen profiles?

**Comment by mfikes** [comment]
It appears that `:tools/deps` can appear in other places in `project.clj`. I'm speculating that with this you could have one profile use one `:tools/deps` and another use a different one.

If that's indeed the case, then it fundamentally allows you to specify different deps based on which profile you are running. And then it is just a matter of revising the syntax a bit so that `:tools/deps` can accept aliases, and you would get aliases for different profiles.

Maybe something along the lines of

```
  :tools/deps {:deps-files [:system :home :project "foo.edn"]
                       :aliases [:test :bench]}
```

Moving to a map would be a breaking change, of course, but perhaps the code could check for a vector first for a transition period.

**Comment by RickMoynihan** [comment]
> It appears that :tools/deps can appear in other places in project.clj.

👍 We're clearly thinking along similar lines, and we already get this capability for free from leiningen e.g. this already works out of the box:

```clojure
(defproject foo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  
  :profiles {:foo {:tools/deps [:system :home] }
                  :test { :tools/deps [:system :home :project "test-deps.edn"] } }   

  :plugins [[lein-tools-deps "0.3.0-SNAPSHOT"]])
```

So the merging you describe should already work.

On the subject of aliases I'd initially thought it might be nice to inherit any `deps.edn` aliases as profiles, but I'm not entirely comfortable with this as a default behaviour; as if you have a lein setup already you might not want aliases clobbering profiles without opting in, so I like the idea of letting users specify aliases as you describe as it would let you combine two deps.edn aliases into a single profile etc.

> Moving to a map would be a breaking change.

Yes agreed.  I'd never intended to ship with the vector, I just never got round to tidying up; and then you and others starting using it despite my best efforts  at trying to discourage people ;-) 

Personally I'm up for just changing this without supporting a deprecation period.  As far as I know you're the biggest user of lein-tools-deps, and we're "VERY ALPHA", and only publishing `-SNAPSHOT`s.

FWIW I'm also up for using the keys you suggest i.e. `:deps-files` and `:aliases` within the `:tools/deps` map.

Whilst we're talking about the change should we also consider naming the key `:lein.tools/deps` or is that too verbose?  I'm worried the tools.deps project might claim ownership of that key name at some point.

**Comment by mfikes** [comment]
With respect to merging, there might be some sort of desired semantics in the case that things collide. For example, the base of the project might specify `[:system :home :project]` and the, say a test profile might add `["test/deps.edn"]` or somesuch. In that case a question might be: if you specify the test profile, do you get `[:system :home :project "test/deps.edn"]` as your merged vector, or is the most-specific level taken?

With respect to aliases, it seems like you generally use those to opt into additional dependencies, or other options. I would bet that aliases at the profile level would be the most common use case. A concrete example, might be a `:aliases [:test]` if you are in a test profile, and this causes perhaps an  `:extra-paths` with a test path, or somesuch.

I agree that making a breaking change at this point is probably no big deal.

There might be a better name than `:deps-files`. Hmm. If the top level key is `:tools/deps` or `:lein.tools/deps`, then keys in the maps could be something like `:files` and `:aliases`. `-Sdescribe` uses `:config-files`, and also has different kinds of aliases, which might make sense over just `:aliases`: So you could have `:resolve-aliases`, `:classpath-aliases`, _etc._ to mimic what would have happened if you used `clj` with `-Ralias...`, `-Calias...` _etc_. Perhaps `-O` and `-M` don't make sense?

`:lein.tools/deps` doesn't sound too verbose.

If you went with all of that, you might end up with config that looks something like like:

```
:lein.tools/deps {:config-files [:system :home :project "foo/deps.edn"]
                            :resolve-aliases [:test]
                            :classpath-alises [:bar]}
```

where perhaps any could be omitted, (where if `:config-files` is omitted, you get the default vector of `[:system :home :project]`, if it is at the "base" of the merge tree, otherwise you effectively get an empty vector?)

**Comment by RickMoynihan** [comment]
> With respect to merging, there might be some sort of desired semantics in the case that things collide. For example, the base of the project might specify [:system :home :project] and the, say a test profile might add ["test/deps.edn"] or somesuch. In that case a question might be: if you specify the test profile, do you get [:system :home :project "test/deps.edn"]

Leiningen should already provide these semantics.  By default you should get a meta-merge, where vectors are`conj`d together so you should end up with `[:system :home :project "test/deps.edn"]`.  You can also use the Leiningen metadata keys to influence the merge should you need to through `^:replace` `^:displace` etc.

I agree with your points about key names though I'll need to remind myself about `-R` and `-C` in tools.deps and exactly how they work; but your proposal here sounds really good.

**Comment by mfikes** [comment]
Looking around at some of the keys used for plugin config, here are some of the ones I'm aware of:

`:cljsbuild`, `:figwheel`, `:doo`, `:tach`

Following that pattern of short, unnamespaced keys, perhaps `:lein-tools-deps`?

**Comment by atroche** [comment]
Could we have an `:aliases` key as well, such that these two configs would be equivalent?

```clj
:lein-tools-deps {:config-files [:system :home :project]
                  :aliases [:test]}
```

```clj
:lein-tools-deps {:config-files [:system :home :project]
                  :resolve-aliases [:test]
                  :classpath-alises [:test]}
```

I think this matches what the `clj` tool does, where `clj -A:test` has the same result as `clj -C:test -R:test` (ignoring JVM / -main options).

**Comment by RickMoynihan** [comment]
> Looking around at some of the keys used for plugin config, here are some of the ones I'm aware of:
> :cljsbuild, :figwheel, :doo, :tach

Personally I'd prefer to use a namespaced keyword here, as I think the other projects were established before clojure 1.9.0, and Rich's speculation talk.  

Whilst `:lein-tools-deps` is ostensibly the same as `:lein.tools/deps` the later has the benefit that you can directly attach a spec to it; where-as un-namespaced keys can't directly be speced without having a level of indirection through `:req-un` etc...

Currently this is a bit of a moot point, as our plugin can't directly use spec anyway because it needs to `:eval-in-leiningen` which depends on clojure 1.8; but I still think encouraging namespacing is a good idea.

**Comment by RickMoynihan** [comment]
> ... Could we have an :aliases key as well ...

@atroche: Yes this would be a good idea, I think as a general principle we should try and match the semantics of tools.deps.

**Comment by RickMoynihan** [comment]
Ok I've confirmed that profiles #34 are merged before middlewares are applied; so leiningen does the right thing for us here.

I think we can easily support `:resolve-aliases` by passing them in to `tdeps/resolve-deps` instead of the empty map `{}` [we currently pass](https://github.com/rickmoynihan/lein-tools-deps/blob/0.4.x/src/lein_tools_deps/plugin.clj#L142).  e.g. if run in the `:dev` profile this `project.clj`:

```clojure
:profiles {:dev {:lein-tools-deps/config {:resolve-aliases [:dev]}}
:lein-tools-deps/config {:resolve-aliases [:foo :bar]}
```

Would be equivalent to `clj -R:foo:bar:dev` (because of leiningen's profile meta merge).  I think this is what we want here.

For `-C` `:classpath-aliases` however we can't rely on the tools.deps library via their `tdeps/make-classpath` function because `lein-tools-deps` currently needs leiningen to [make the classpath](https://github.com/technomancy/leiningen/blob/c039f1a3790b02ea5754fa9a60b51284756ec762/leiningen-core/src/leiningen/core/classpath.clj#L591) for us following leiningens semantics, e.g. including `:source-paths`, checkouts etc on there.  

So to support `:classpath-aliases` I think we will need to effectively implement them ourselves, mapping `:extra-paths` onto lein's `:source-paths` and handling tools.deps `:classpath-overrides` by removing any overrides from our `:dependencies`, and instead adding the locations to our `:source-paths`.  To do this we should however make use of `tdeps/combine-aliases` to resolve the final set of `:extra-paths` and `:classpath-overrides` for us, and just do the final mapping into leiningen terms ourselves.

I'm not yet sure what the implications of supporting `:classpath-aliases` are.  Currently `lein-tools-deps` only uses the `tdeps/resolve-deps` function and we don't call `tdeps/make-classpath` which is the function that receives `:classpath-aliases` e.g.

```clojure
(combine-aliases '{:aliases {:foo {:classpath-overrides {org.clojure/clojure "foo"} :extra-paths ["flop"]} :bar {:classpath-overrides {org.clojure/clojure "foobar"} :extra-paths ["flip"]}}} [:foo :bar]) 
;; =>
{:classpath-overrides {org.clojure/clojure "foobar"},
 :extra-paths ["flop" "flip"]}
```

I also see little benefit in supporting `:main-aliases` or `:jvm-option-aliases` just now though they may have some limited usecases, if for example you used `lein run`.

**Comment by RickMoynihan** [comment]
This is supported as of https://github.com/RickMoynihan/lein-tools-deps/releases/tag/0.4.1

**Comment by ezmiller** [comment]
Is there an example for how to set aliases up here? I've not been able to get them to work. It's not clear to me where I need to define the aliases and with which keywords of those listed in the README. An example would be a great help.
