### ISSUE TITLE
Heroku does not accept lein-tools-deps

### ISSUE THREAD

**Issue by AlexAti** [RickMoynihan/lein-tools-deps#79]
The reason is that lein-tools-deps looks for the clojure cli command instead of executing the binaries retrieved by lein.

I have created a minimal project that reproduces this at https://github.com/AlexAti/lein-with-deps-project , which gives the following stacktrace when trying to deploy to Heroku:

```
       java.io.IOException: Cannot run program "clojure" (in directory "/tmp/build_54f7a078803f22e06807db4f6e663fb4"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start (ProcessBuilder.java:1048)
           java.lang.Runtime.exec (Runtime.java:620)
           clojure.java.shell$sh.invokeStatic (shell.clj:113)
           clojure.java.shell$sh.doInvoke (shell.clj:79)
           clojure.lang.RestFn.invoke (RestFn.java:421)
           lein_tools_deps.env$scrape_clojure_env.invokeStatic (env.clj:32)
           lein_tools_deps.env$scrape_clojure_env.invoke (env.clj:27)
           clojure.lang.AFn.applyToHelper (AFn.java:154)
           clojure.lang.AFn.applyTo (AFn.java:144)
```

I'm trying in parallel to create a more robust buildpack for clojure at https://github.com/AlexAti/heroku-buildpack-clojure (still not working), but I think that, as leiningen is pulling already a version of clojure, lein-tools-deps should perhaps by default point to those binaries, instead of expecting that clojure is not only brought by leiningen but also locally installed, shouldn't it? This was also discussed on #62, #74 and #75 , but with the premise that clojure is installed *somewhere*, not brought by leiningen.

Does that make sense? I'm happy to help but I'd need some pointers :)

**Comment by RickMoynihan** [comment]
Hi your problem makes sense but this isn't a bug; `lein-tools-deps` has a required dependency on the clojure CLI tools, because `tools.deps` itself depends on these.

Leiningen has no dependency on the clojure CLI tools, so we can't use what leiningen does.

**Comment by realgenekim** [comment]
@RickMoynihan Thanks for your wonderful work — over the last year, I've been marveling at the benefits that tools.deps enable (most recently, using git coordinates instead of having to install local maven artifacts!)

@AlexAti Did you ever get this to work?  I see that the Heroku folks updated the buildpack, but I found that in order to get a Cursive REPL to work, I have to manually set `:clojure-executables ["/usr/local/bin/clojure"]`.

However, this now causes Heroku `lein uberjar` builds to fail — at build time, Heroku installs the clj/clojure binaries in a temporary directory (but still in $PATH).  So I get the following error:

```
remote:        clojure.lang.ExceptionInfo: Could not find clojure executable        
remote:         at clojure.core$ex_info.invokeStatic (core.clj:4617)        
```

I think this is relevant to what @mfikes writes https://gist.github.com/mfikes/f803fef3013927c376063a3d72b69d60 and https://github.com/RickMoynihan/lein-tools-deps/pull/31.

Is there a way to get a `:clojure-executables` entry that simultaneously lets Cursive REPL to run, as well as Heroku builds to run?  (I tried `{:clojure-executables ["/usr/local/bin/clojure" "clojure"]}`, thinking that an unqualified path might work, but alas, no...)

Many thanks in advance!!!

**Comment by RickMoynihan** [comment]
@realgenekim thanks for the compliment.

> Is there a way to get a :clojure-executables entry that simultaneously lets Cursive REPL to run, as well as Heroku builds to run? (I tried {:clojure-executables ["/usr/local/bin/clojure" "clojure"]}, thinking that an unqualified path might work, but alas, no...)

Not sure why that doesn't work, but I don't use either Heroku or Cursive.  

You might also try having two different different lein profiles one for dev/cursive and the other for heroku.  You may need to use `^:replace` or `^:displace` metadata to ensure the vectors for `:clojure-executables` aren't concatenated.

**Comment by AlexAti** [comment]
@RickMoynihan perhaps you can put :clojure-executables in your profile.clj?

But answering your question, I went in other direction, by modifying the heroku clojure buildpack. Some of the changes were taken into the standard version: https://github.com/heroku/heroku-buildpack-clojure/pull/61.

Perhaps you can also clone the buildpack and do changes to it to solve your problem? To me it ended up being quite straightforward!

**Comment by RickMoynihan** [comment]
> perhaps you can put :clojure-executables in your profile.clj?

Yes, you can specify the profiles in any of the standard leiningen places and it should work.

> Perhaps you can also clone the buildpack and do changes to it to solve your problem?

What problem?  You opened this issue not me 😄

**Comment by AlexAti** [comment]
> What problem? You opened this issue not me 😄

Hahaha I should have written @realgenekim not @RickMoynihan, who is the one with the problem :). I was just suggesting a way for him to specify a local :clojure-executables that is not sent to heroku (as it remains out of the actual project configuration).
